In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

train_dataset = pd.read_csv('Training.csv')
test_dataset = pd.read_csv('Testing.csv')
X = train_dataset.iloc[:, 1:132].values
y = train_dataset.iloc[:, 132].values
X

array([[1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 1, 1]])

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_y_1 = LabelEncoder()
y = labelencoder_y_1.fit_transform(y)
y







array([15, 15, 15, ..., 38, 35, 27])

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
y_train



array([ 0,  5, 40, ...,  4,  3, 10])

In [0]:


#importing the keras libraries and keras
import keras
from keras.models import Sequential
from keras.layers import Dense

#initializing the ANN
classifier = Sequential()

#adding an input layer and the first hidden layer
classifier.add(Dense(54, input_shape =(131,), activation = 'relu'))


classifier.add(Dense(108, activation = 'relu'))

classifier.add(Dense(49, activation = 'softmax'))

classifier.summary()
classifier.compile(optimizer = 'adam' , loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
classifier.fit(X_train,y_train,batch_size = 10 ,epochs=20)
_, accuracy = classifier.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))


Model: "sequential_47"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_138 (Dense)            (None, 54)                7128      
_________________________________________________________________
dense_139 (Dense)            (None, 108)               5940      
_________________________________________________________________
dense_140 (Dense)            (None, 49)                5341      
Total params: 18,409
Trainable params: 18,409
Non-trainable params: 0
_________________________________________________________________
Epoch 1/20
3444/3444 [==============================] - 1s 428us/step - loss: 0.6548 - acc: 0.9010
Epoch 2/20
3444/3444 [==============================] - 1s 171us/step - loss: 0.0072 - acc: 0.9997
Epoch 3/20
3444/3444 [==============================] - 1s 161us/step - loss: 0.0023 - acc: 1.0000
Epoch 4/20
3444/3444 [==============================] - 1s 159us/step - loss: 0.00

In [0]:
predictions = classifier.predict_classes(X_test)
# summarize the first 5 cases
for i in range(30):
	print('%s => %d (expected %d)' % (X_test[i].tolist(), predictions[i], y_test[i]))

[-0.44018272556870386, -0.1532219592500851, -0.2148779641789066, -0.15519548261265204, -0.4415919720880603, -0.4029087623849895, -0.21413744092907006, -0.207374636478604, -0.1450844954543007, -0.15322195925008503, 1.2530559659214406, -0.20964902323482476, -0.14508449545430085, -0.815706550185446, -0.1581138830084164, -0.16659204536600708, -0.15617376188860663, -0.2214509239697931, -0.3211526326420437, -0.22289005275513954, -0.327168973355255, -0.15811388300841642, -0.15617376188860665, -0.3532068261669709, -0.6189770029011378, -0.14715738229745487, 3.219679585558743, 2.4729946379519414, -0.14920388317111233, -0.2126500184552416, -0.5563323677641376, -0.4777503152966584, -0.35941664940407914, -0.5603590716697572, -0.5581221916456146, -0.16659204536600708, -0.2250347407251929, -0.21413744092907114, -0.5105045877503933, -0.35838577953438916, -0.2779567073943221, -0.15811388300841653, -0.44674604325973394, -0.1542115846551545, 0.0, -0.15714652793078512, -0.2736902757519815, -0.413558051324